name: "姫川雪質研究会 公式サイト"
short_name: "姫川雪研"
description: "姫川流域地域を調査する群馬県の団体。活動内容は多岐にわたる……予定。"
author: "姫川雪質研究会"
url:
# pages以下をどのようなURLで公開するか指定
# `${scheme}://${host}${path}/`    
# デフォルト例: https://tamaina.github.io/
#           ↓                  # 右コメント例: https://maqz.example.com/maqz/
  path: ""                      # "/maqz"
  host: "himekawa-sekken.github.io"     # "maqz.example.com"    
  scheme: https                 # "https"
language: ja
pages_src:
  path: "./pages/"
  src: "**/*.{html,htm,pug,md}"
page_namingrule: name
theme_color:
  primary: "#060034"
  secondary: "#f9f9ff"
# theme_colorはmanifest用なのでスタイルシートのprimaryなどとは別
default:
  template: default
social_media:
# social_mediaは過去の遺物
  twitter:
    stalk: himekawa_snow
    share: true
    card: true
  LINE:
    stalk: false
    share: true
  facebook:
    stalk: false
    share: true
  flickr:
    stalk: false
    share: false
  github:
    stalk: himekawa-sekken
    share: false
  share_button: true
rss:
  root: "/activities/"      # blogフォルダの記事を配信(pages直下(ルート)は"/")
  template: "activity"    # blogテンプレートを指定している記事を配信
# 並べかえのために各ページのFrontMatterにdate: (JSON日時)を指定する必要があります
# 無効にしたかったらfalseにしてroot:,template:の行頭に#
disqus: false
# 無効にしたかったらfalse
ga: UA-134082528-1
# 無効にしたかったらfalse
sidebar: true
# サイドバーは無効にできる
manifest:
  display: standalone
meta_pages: ['404', 'offline']
# システムで利用するページを列挙
sw: "js|css|png|jpeg|jpg|svg|svgz|woff2"